title: _joe eldredge # your name (or website title) here
logo: "/images/logo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I made ^ this mosaic ^ using Python!
  <br><br>
  Please browse my site to see what I have been up to - my interests are managing data or projects involving data.
  <br><br>
  <a href="https://www.linkedin.com/in/joseph-eldredge-75ab6349/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
