#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 12 21:48:06 2021

@author: Joe
"""

"NLP Practice"

import re
import pandas as pd
#import nltk
from pandas import *

response='https://www.transit.dot.gov/sites/fta.dot.gov/files/2020-10/2019%20Facility%20Inventory.xlsx'
df=pd.read_excel(response)


al=df[['Agency Name','Year Built','Condition Assessment Date','Notes']]
Notes_only=al[al.Notes.notnull()]
#Notes_only #6474 facilities have associated notes

#Useful Life Using Regex Tokenization

Notes_year=Notes_only[Notes_only['Notes'].str.contains('[0-9]{4}')] #497 have rows that are probably years
Year_Note=Notes_year.lore.findall('\S[0-9]{4}',Notes_only['Notes'][1])
comparison=Notes_year['Year Built'] - Notes_year['[0-9]{4}']
Notes_only['Notes']
